FROM node:lts-alpine3.16 as build
WORKDIR /workspace/app
COPY package.json .
COPY package-lock.json .

RUN npm install

COPY public/ public/
COPY src/ src/
COPY index.html ./index.html
COPY vite.config.js ./vite.config.js

RUN npm run build


FROM nginx:1.21.3-alpine as prod
COPY --from=build /workspace/app/dist /usr/share/nginx/html
COPY ./nginx.conf /etc/nginx/conf.d/default.conf