name: Example workflow using Snyk
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: curl https://static.snyk.io/cli/latest/snyk-linux -o snyk
      - name: Install Snyk
        run: | 
          chmod +x ./snyk
          mv ./snyk /usr/local/bin/
          snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Run the Maven verify phase
        run: cd /sqlBinder && mvn --batch-mode --update-snapshots verify
      - run: pwd
      - name: Run Snyk to check for vulnerabilities
        run: snyk test --all-projects